const SYSTEM_TEMPLATE_ID = "uaams-system-template-v2";
const SYSTEM_TEMPLATE_RENDER_MODE = "generated";
const SYSTEM_TEMPLATE_FILE_NAME = "uaams-generated-application-template.svg";
const SYSTEM_TEMPLATE_MIME_TYPE = "image/svg+xml";
const SYSTEM_TEMPLATE_PAGE_WIDTH = 1240;
const SYSTEM_TEMPLATE_PAGE_HEIGHT = 1754;

const SYSTEM_TEMPLATE_COLORS = {
  page: "#ffffff",
  pageBorder: "#cbd5e1",
  headerFill: "#e8f4ef",
  headerAccent: "#0f766e",
  sectionFill: "#f8fafc",
  sectionBorder: "#d7e0ea",
  fieldFill: "#ffffff",
  fieldBorder: "#b8c7d6",
  label: "#475569",
  ink: "#153955",
  muted: "#64748b",
};

const SYSTEM_TEMPLATE_STATIC_TEXT = [
  {
    text: "UAAMS",
    x: 72,
    y: 62,
    fontSize: 42,
    fontWeight: "700",
    color: SYSTEM_TEMPLATE_COLORS.headerAccent,
  },
  {
    text: "University Admission Application",
    x: 72,
    y: 112,
    fontSize: 30,
    fontWeight: "700",
    color: SYSTEM_TEMPLATE_COLORS.ink,
  },
  {
    text: "System generated template for mapped admission form data",
    x: 72,
    y: 150,
    fontSize: 18,
    fontWeight: "400",
    color: SYSTEM_TEMPLATE_COLORS.muted,
  },
  {
    text: "Official Application Record",
    x: 880,
    y: 86,
    fontSize: 22,
    fontWeight: "700",
    color: SYSTEM_TEMPLATE_COLORS.ink,
  },
  {
    text: "Generated by UAAMS",
    x: 880,
    y: 122,
    fontSize: 16,
    fontWeight: "400",
    color: SYSTEM_TEMPLATE_COLORS.muted,
  },
  {
    text: "Applicant declaration: the information provided in this application is accurate to the best of my knowledge.",
    x: 70,
    y: 1532,
    fontSize: 15,
    fontWeight: "400",
    color: SYSTEM_TEMPLATE_COLORS.muted,
  },
];

const SYSTEM_TEMPLATE_SECTIONS = [
  { title: "University", x: 52, y: 218, width: 1136, height: 252 },
  { title: "Student Details", x: 52, y: 510, width: 1136, height: 400 },
  { title: "Academic Details", x: 52, y: 950, width: 1136, height: 154 },
  { title: "Additional Form Responses", x: 52, y: 1140, width: 1136, height: 220 },
  { title: "Documents", x: 52, y: 1390, width: 1136, height: 142 },
  { title: "Declaration", x: 52, y: 1564, width: 1136, height: 140 },
];

const SYSTEM_TEMPLATE_FIELD_BLOCKS = [
  {
    id: "system-university-name",
    fieldId: "meta.universityName",
    label: "University Name",
    x: 70,
    y: 286,
    width: 500,
    height: 54,
    fontSize: 22,
  },
  {
    id: "system-program",
    fieldId: "meta.program",
    label: "Program",
    x: 590,
    y: 286,
    width: 345,
    height: 54,
    fontSize: 20,
  },
  {
    id: "system-application-code",
    fieldId: "meta.applicationCode",
    label: "Application Code",
    x: 955,
    y: 286,
    width: 210,
    height: 54,
    fontSize: 18,
  },
  {
    id: "system-university-contact",
    fieldId: "meta.universityContactSummary",
    label: "University Contact",
    x: 70,
    y: 382,
    width: 1095,
    height: 72,
    fontSize: 18,
    valueInsetY: 12,
  },
  {
    id: "system-student-name",
    fieldId: "meta.studentName",
    label: "Full Name",
    x: 70,
    y: 570,
    width: 500,
    height: 54,
    fontSize: 22,
  },
  {
    id: "system-cnic",
    fieldId: "4",
    label: "CNIC / B-Form",
    x: 590,
    y: 570,
    width: 260,
    height: 54,
    fontSize: 20,
  },
  {
    id: "system-dob",
    fieldId: "meta.studentBirthDate",
    label: "Date of Birth",
    x: 870,
    y: 570,
    width: 295,
    height: 54,
    fontSize: 20,
  },
  {
    id: "system-email",
    fieldId: "2",
    label: "Email Address",
    x: 70,
    y: 666,
    width: 500,
    height: 54,
    fontSize: 19,
  },
  {
    id: "system-phone",
    fieldId: "3",
    label: "Phone Number",
    x: 590,
    y: 666,
    width: 260,
    height: 54,
    fontSize: 20,
  },
  {
    id: "system-gender",
    fieldId: "meta.studentGender",
    label: "Gender",
    x: 870,
    y: 666,
    width: 135,
    height: 54,
    fontSize: 20,
  },
  {
    id: "system-nationality",
    fieldId: "meta.studentNationality",
    label: "Nationality",
    x: 1025,
    y: 666,
    width: 140,
    height: 54,
    fontSize: 19,
  },
  {
    id: "system-address",
    fieldId: "meta.studentAddressLine",
    label: "Address",
    x: 70,
    y: 762,
    width: 685,
    height: 72,
    fontSize: 18,
    valueInsetY: 12,
  },
  {
    id: "system-city",
    fieldId: "meta.studentCity",
    label: "City",
    x: 775,
    y: 762,
    width: 185,
    height: 54,
    fontSize: 19,
  },
  {
    id: "system-province",
    fieldId: "meta.studentProvince",
    label: "Province",
    x: 980,
    y: 762,
    width: 185,
    height: 54,
    fontSize: 19,
  },
  {
    id: "system-postal-code",
    fieldId: "meta.studentPostalCode",
    label: "Postal Code",
    x: 775,
    y: 852,
    width: 185,
    height: 54,
    fontSize: 19,
  },
  {
    id: "system-status",
    fieldId: "meta.applicationStatus",
    label: "Application Status",
    x: 980,
    y: 852,
    width: 185,
    height: 54,
    fontSize: 19,
  },
  {
    id: "system-matric-marks",
    fieldId: "7",
    label: "Matric Marks",
    x: 70,
    y: 1018,
    width: 300,
    height: 54,
    fontSize: 21,
  },
  {
    id: "system-inter-marks",
    fieldId: "8",
    label: "FSc / A-Level Marks",
    x: 390,
    y: 1018,
    width: 300,
    height: 54,
    fontSize: 21,
  },
  {
    id: "system-test-score",
    fieldId: "testScore",
    label: "Test Score",
    x: 710,
    y: 1018,
    width: 220,
    height: 54,
    fontSize: 21,
  },
  {
    id: "system-aggregate",
    fieldId: "meta.aggregate",
    label: "Aggregate",
    x: 950,
    y: 1018,
    width: 215,
    height: 54,
    fontSize: 21,
  },
  {
    id: "system-other-fields",
    fieldId: "meta.dynamicFieldsSummary",
    label: "Additional Field Values",
    x: 70,
    y: 1206,
    width: 1095,
    height: 130,
    fontSize: 17,
    valueInsetY: 12,
  },
  {
    id: "system-profile-picture",
    fieldId: "9",
    label: "Profile Picture",
    x: 70,
    y: 1452,
    width: 255,
    height: 50,
    fontSize: 16,
  },
  {
    id: "system-domicile",
    fieldId: "10",
    label: "Domicile Certificate",
    x: 345,
    y: 1452,
    width: 255,
    height: 50,
    fontSize: 16,
  },
  {
    id: "system-matric-result",
    fieldId: "11",
    label: "Matric Result",
    x: 620,
    y: 1452,
    width: 255,
    height: 50,
    fontSize: 16,
  },
  {
    id: "system-inter-result",
    fieldId: "12",
    label: "Inter Result",
    x: 895,
    y: 1452,
    width: 270,
    height: 50,
    fontSize: 16,
  },
  {
    id: "system-signature",
    fieldId: "meta.studentSignature",
    label: "Applicant Signature",
    x: 70,
    y: 1628,
    width: 530,
    height: 58,
    fontSize: 24,
  },
  {
    id: "system-applied-date",
    fieldId: "meta.appliedDate",
    label: "Date",
    x: 815,
    y: 1628,
    width: 350,
    height: 58,
    fontSize: 22,
  },
];

const escapeSvg = (value = "") =>
  String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const renderSvgText = ({ text, x, y, fontSize, fontWeight = "400", color }) =>
  `<text x="${x}" y="${y + fontSize}" font-family="Arial, Helvetica, sans-serif" font-size="${fontSize}" font-weight="${fontWeight}" fill="${color}">${escapeSvg(text)}</text>`;

const renderSvgRect = ({
  x,
  y,
  width,
  height,
  fill = "none",
  stroke = "none",
  strokeWidth = 0,
  radius = 0,
}) =>
  `<rect x="${x}" y="${y}" width="${width}" height="${height}" rx="${radius}" ry="${radius}" fill="${fill}" stroke="${stroke}" stroke-width="${strokeWidth}" />`;

const createMappingFromFieldBlock = (field) => {
  const fontSize = Number(field.fontSize || 18);
  const valueInsetX = Number(field.valueInsetX ?? 14);
  const valueInsetY = Number(
    field.valueInsetY ?? Math.max(10, Math.round((Number(field.height || 54) - fontSize) / 2)),
  );

  return {
    id: field.id,
    fieldId: field.fieldId,
    label: field.label,
    x: Number(field.x) + valueInsetX,
    y: Number(field.y) + valueInsetY,
    width: Math.max(24, Number(field.width) - valueInsetX * 2),
    height: Math.max(fontSize + 4, Number(field.height) - valueInsetY - 6),
    fontSize,
    textAlign: field.textAlign || "left",
    color: field.color || SYSTEM_TEMPLATE_COLORS.ink,
    page: 1,
  };
};

const SYSTEM_TEMPLATE_FIELD_MAPPINGS = SYSTEM_TEMPLATE_FIELD_BLOCKS.map(createMappingFromFieldBlock);

const buildSystemTemplateSvg = () => {
  const parts = [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${SYSTEM_TEMPLATE_PAGE_WIDTH}" height="${SYSTEM_TEMPLATE_PAGE_HEIGHT}" viewBox="0 0 ${SYSTEM_TEMPLATE_PAGE_WIDTH} ${SYSTEM_TEMPLATE_PAGE_HEIGHT}">`,
    renderSvgRect({
      x: 0,
      y: 0,
      width: SYSTEM_TEMPLATE_PAGE_WIDTH,
      height: SYSTEM_TEMPLATE_PAGE_HEIGHT,
      fill: SYSTEM_TEMPLATE_COLORS.page,
    }),
    renderSvgRect({
      x: 28,
      y: 28,
      width: SYSTEM_TEMPLATE_PAGE_WIDTH - 56,
      height: SYSTEM_TEMPLATE_PAGE_HEIGHT - 56,
      fill: SYSTEM_TEMPLATE_COLORS.page,
      stroke: SYSTEM_TEMPLATE_COLORS.pageBorder,
      strokeWidth: 2,
      radius: 8,
    }),
    renderSvgRect({
      x: 52,
      y: 48,
      width: 1136,
      height: 132,
      fill: SYSTEM_TEMPLATE_COLORS.headerFill,
      stroke: "#9fd6ca",
      strokeWidth: 1.5,
      radius: 8,
    }),
    `<line x1="840" y1="70" x2="840" y2="158" stroke="#9fd6ca" stroke-width="2" />`,
  ];

  SYSTEM_TEMPLATE_STATIC_TEXT.forEach((textBlock) => {
    parts.push(renderSvgText(textBlock));
  });

  SYSTEM_TEMPLATE_SECTIONS.forEach((section) => {
    parts.push(
      renderSvgRect({
        x: section.x,
        y: section.y,
        width: section.width,
        height: section.height,
        fill: SYSTEM_TEMPLATE_COLORS.sectionFill,
        stroke: SYSTEM_TEMPLATE_COLORS.sectionBorder,
        strokeWidth: 1.5,
        radius: 8,
      }),
    );
    parts.push(
      renderSvgText({
        text: section.title,
        x: section.x + 18,
        y: section.y + 18,
        fontSize: 18,
        fontWeight: "700",
        color: SYSTEM_TEMPLATE_COLORS.headerAccent,
      }),
    );
  });

  SYSTEM_TEMPLATE_FIELD_BLOCKS.forEach((field) => {
    parts.push(
      renderSvgText({
        text: field.label,
        x: field.x,
        y: field.y - 24,
        fontSize: 14,
        fontWeight: "700",
        color: SYSTEM_TEMPLATE_COLORS.label,
      }),
    );
    parts.push(
      renderSvgRect({
        x: field.x,
        y: field.y,
        width: field.width,
        height: field.height,
        fill: SYSTEM_TEMPLATE_COLORS.fieldFill,
        stroke: SYSTEM_TEMPLATE_COLORS.fieldBorder,
        strokeWidth: 1.25,
        radius: 6,
      }),
    );
  });

  parts.push("</svg>");
  return parts.join("");
};

const buildSystemTemplateDataUrl = () =>
  `data:${SYSTEM_TEMPLATE_MIME_TYPE};base64,${Buffer.from(buildSystemTemplateSvg(), "utf8").toString("base64")}`;

const resolveSystemTemplatePublicUrl = () => buildSystemTemplateDataUrl();

const getSystemApplicationTemplate = () => ({
  id: SYSTEM_TEMPLATE_ID,
  name: "UAAMS Generated Application Template",
  renderMode: SYSTEM_TEMPLATE_RENDER_MODE,
  fileUrl: resolveSystemTemplatePublicUrl(),
  fileName: SYSTEM_TEMPLATE_FILE_NAME,
  mimeType: SYSTEM_TEMPLATE_MIME_TYPE,
  pageWidth: SYSTEM_TEMPLATE_PAGE_WIDTH,
  pageHeight: SYSTEM_TEMPLATE_PAGE_HEIGHT,
  fieldMappings: SYSTEM_TEMPLATE_FIELD_MAPPINGS,
});

const SYSTEM_MAPPED_FIELD_IDS = new Set(
  SYSTEM_TEMPLATE_FIELD_MAPPINGS.map((mapping) => String(mapping?.fieldId || "").trim()).filter(
    Boolean,
  ),
);

module.exports = {
  SYSTEM_TEMPLATE_ID,
  SYSTEM_TEMPLATE_RENDER_MODE,
  SYSTEM_TEMPLATE_FILE_NAME,
  SYSTEM_TEMPLATE_MIME_TYPE,
  SYSTEM_TEMPLATE_PAGE_WIDTH,
  SYSTEM_TEMPLATE_PAGE_HEIGHT,
  SYSTEM_TEMPLATE_COLORS,
  SYSTEM_TEMPLATE_STATIC_TEXT,
  SYSTEM_TEMPLATE_SECTIONS,
  SYSTEM_TEMPLATE_FIELD_BLOCKS,
  SYSTEM_TEMPLATE_FIELD_MAPPINGS,
  SYSTEM_MAPPED_FIELD_IDS,
  buildSystemTemplateSvg,
  buildSystemTemplateDataUrl,
  resolveSystemTemplatePublicUrl,
  getSystemApplicationTemplate,
};
