name: Backend CD

on:
   workflow_run:
    workflows: ["ci.yml"] # Exact name of your CI file
    types:
      - completed

jobs:
  deploy:
    name: Deploy backend to Render
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deploy hook
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
